version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.10.2
    container_name: paperless
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      PAPERLESS_REDIS: redis://nc-redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBNAME: $PAPERLESS_DBNAME
      PAPERLESS_DBUSER: $PAPERLESS_DBUSER
      PAPERLESS_DBPASS: $PAPERLESS_DBPASS
      PAPERLESS_URL: https://paperless.$MEELSNET_DOMAIN
    volumes:
      - ${CONF_DIR}/paperless/data:/usr/src/paperless/data
      - ${DMS_DIR}/media:/usr/src/paperless/media
      - ${DMS_DIR}/consume:/usr/src/paperless/consume
    networks:
      - traefik_proxy
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.entrypoints=https"
      - "traefik.http.routers.paperless.rule=Host(`paperless.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.paperless.tls=true"
      - "traefik.http.routers.paperless.middlewares=chain-no-auth@file"
      - "traefik.http.routers.paperless.service=paperless"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
