version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - CREATE_TUN_DEVICE=true
      - DROP_DEFAULT_ROUTE=true
      - HEALTH_CHECK_HOST=google.com
      - LOCAL_NETWORK=192.168.0.0/24
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - DOWNLOAD_QUEUE_ENABLED=true
      - QUEUE_STALLED_ENABLED=true
      # - TRANSMISSION_ENCRYPTION=2
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST=127.0.0.1,192.168.*.*
      - TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=true
      - TRANSMISSION_RPC_USERNAME=${TORRENT_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${TORRENT_PASSWORD}
      - TRANSMISSION_PORT_FORWARDING_ENABLED=true
      # - TRANSMISSION_RATIO_LIMIT=0.01
      # - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_IDLE_SEEDING_LIMIT=30
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSION_UTP_ENABLED=false
      # - TRANSMISSION_BLOCKLIST_ENABLED=true
      # - TRANSMISSION_BLOCKLIST_URL=http://john.bitsurge.net/public/biglist.p2p.gz
      - TRANSMISSION_WEB_UI=flood-for-transmission
      # - WEBPROXY_ENABLED=false
    volumes:
      - ${CONF_DIR}/transmission/data:/data
      - ${CONF_DIR}/transmission/config:/config
      - ${DOWNLOAD_DIR}/completed:/data/completed
      - ${DOWNLOAD_DIR}/incomplete:/data/incomplete
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik_proxy
    expose:
      - 9091
    ports:
      - 51413:51413
      - 51413:51413/udp
    dns:
      - 1.1.1.1
      - 1.0.0.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.entrypoints=https"
      - "traefik.http.routers.transmission.rule=Host(`transmission.$MEELSNET_DOMAIN`) || Host(`torrents.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.transmission.tls=true"
      - "traefik.http.routers.transmission.middlewares=chain-no-auth@file"
      - "traefik.http.routers.transmission.service=transmission"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    logging:
      driver: "json-file"
      options:
        max-size: "10m"