version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  jellyfin:
    image: jellyfin/jellyfin:20231027.11-unstable
    container_name: jellyfin
    restart: unless-stopped
    hostname: jellyfin
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=http://jellyfin.$MEELSNET_DOMAIN
    volumes:
      - ${CONF_DIR}/jellyfin/config:/config
      - ${CONF_DIR}/jellyfin/cache:/cache
      - ${MEDIA_DIR}:/media
    networks:
      - traefik_proxy
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
      # - 1900:1900/udp
      - 7359:7359/udp
    expose:
      - 8920
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.middlewares=chain-no-auth@file"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    devices:
      - /dev/dri:/dev/dri
