version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:7.1.1
    container_name: recyclarr
    restart: unless-stopped
    user: $PUID:$PGID
    environment:
      - TZ=$TZ
    volumes:
      - $CONF_DIR/recyclarr/config:/config
    networks:
      - traefik_proxy
